name: Build Lint Test (BLT)
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches-ignore:
      - pacman*
    paths-ignore:
      - "examples/**"
      - "Dockerfile"
  pull_request:

jobs:
  build:
    name: Build and test go-alpm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Build and tests
        run: ./testdata/ci/test.sh
