name: Build versus testing
# This workflow is triggered on pushes to the repository.
on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    name: Build and test go-alpm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1#
      - name: Run Build and tests
        run: (curl https://www.archlinux.org/feeds/packages/all/testing/ | grep pacman) && ./testdata/ci/test.sh testdata/ci/testing.Dockerfile testing || exit 0
